pmndrs/react-spring

src/Trail.js, src/animated/AnimatedValue.js, src/animated/SpringAnimation.js, src/index.js
Hey @drcmda congratulations to make a awesome project like this, thanks very much.
=> Removing unnecessary imports.

.size-snapshot.json, package.json, rollup.config.js, src/Parallax.js, yarn.lock
Polyfill is also required until major release with 16.4 restriction.
=> Add new context api polyfill and migrate paralax

examples/README.md
The demo fails to start otherwise
=> Instruct to install react-spring dependencies

.size-snapshot.json, src/Parallax.js
This simple pull request should avoid repeating some string many times. :)
=> Preventing harded code.

.size-snapshot.json, src/Transition.js
=> Pass Transition onRest through to Spring

.size-snapshot.json, examples/yarn.lock, src/Spring.js, src/animated/AnimatedInterpolation.js, src/animated/Globals.js, src/animated/createAnimatedComponent.js, src/animated/targets/react-dom/index.js, src/animated/targets/react-native/index.js, yarn.lock
This diff makes Globals statically analysable
=> Prefer named exports for globals

index.d.ts, package.json
=> WIP: Add TypeScript definition

index.d.ts
Updated Spring types. Didn't touch other components since I haven't used them yet.
=> Update Spring types

.size-snapshot.json, API.md, index.d.ts, package.json, src/Spring.js, yarn.lock
Hi, I'm adding `onStart` callback because I'd like to know the time that animation starts to animate, which allows me to optimize the rendering performance.
=> Add onStart callback

src/Transition.js
=> Compare 'keys' as Strings, allow 0 as key

.size-snapshot.json, src/animated/createAnimatedComponent.js, tests/test.js
Resolves https://github.com/drcmda/react-spring/issues/184
=> Feature: Add ref forwarding to animated components

src/animated/AnimatedWithChildren.js, src/targets/web/index.js
This will remove those pesky strings in production builds 😉
=> Wrapped console.warn calls with NODE_ENV check

API.md
Stole it from readme. Should be in API description as well.
=> Add description for update prop of Transition component

.size-snapshot.json, src/targets/web/globals.js
=> Tweak unitless

.gitignore, .size-snapshot.json, package.json, src/addons/DurationTrail.js, tests/Keyframes.test.js, tests/Spring.test.js, tests/__snapshots__/Keyframes.test.js.snap, tests/__snapshots__/Spring.test.js.snap, tests/addons/DurationTrail.test.js, tests/addons/__snapshots__/DurationTrail.test.js.snap, tests/setupTests.js, yarn.lock
A few notes:
* added webpack/webpack-dev-server as `npm install` failed without them. 
* added enzyme and enyzme-adapter-react-16 for react specific testing.
* changed a few of the npm scripts to print out better coverage.
* added snapshot/smoke testing for successful proof of concept.
Don't know if I'm adhering to your preferred contribution guidelines, but since I didn't find any, I figured I'd give it my best effort.
Expect a few more soon. 😄
=> added enzyme testing framework and a few examples for unit tests

src/shared/helpers.js
Solves issue when Number object have new prototype function
=> Update shallowEquals to handle numbers the same way as strings

.size-snapshot.json, src/Transition.js
=> Fix updating items in Transition

documentation/Hooks-manual.mdx
Just a small error I found when reading through the documentation.
=> Small spelling/punctuation fix

documentation/Introduction.mdx
=> Corrects Scott's last name Update Introduction.mdx

documentation/Gotchas.mdx
From: https://github.com/drcmda/react-spring/issues/330
Feel free to tweak the formatting / language to your liking.
=> Add polyfill documentation

src/addons/KeyframesHook.js, src/addons/SpringHook.js, src/addons/TrailHook.js, src/addons/TransitionHook.js, src/addons/index.js, stories/index.css, stories/tests/trailHook.js, stories/tests/transitionhook.js
=> implementing transition hook. WIP

.size-snapshot.json, src/targets/native/AnimatedTransform.js
The transform property in style didn't work in react-native.
Resolves #361
=> Fix react-native transform

.size-snapshot.json, src/animated/AnimatedProps.js, src/animated/Globals.js, src/targets/native/AnimatedReactNativeStyle.js, src/targets/native/index.js
Resolves #337
I did this PR to familiarize myself with the codebase and its use in a react-native context.
Let me know what you think of it
=> Support react-native style format

documentation/What-is-new.mdx
=> add medium article

examples/demos/hooks/gestures-pager/index.js
change prevents a crash on unmounting of this component
=> fix gestures-pager demo

readme.md
=> Fix documentation link in readme.md

types/native-hooks.d.ts, types/native.d.ts
TODO mention change on release notes
=> Fix native hooks export

src/targets/native/index.js
Fix #504 
Using eslint/tslint could help with this kind of bug
=> Fix ApplyAnimatedValues is not defined

types/web.d.ts
=> More type fixes

types/web.d.ts
=> Fix useTransition type definition

documentation/introduction.mdx
Small typo on the introduction (animatead => animated)
=> fix(doc): typo

types/web.d.ts
This is my best guess for the typings. Feedback is very welcome.
Fixes #499
=> Typings for useSprings

types/web.d.ts
Also allow single item to be passed in useTransition.
Cheers :beers:
=> Fix: Type for useTransition

src/animated/Controller.js, src/animated/FrameLoop.js
Was just trying converting some files to ts to try and catch things that became obvious but not too complex and saw this
=> remove unused param from stop method on Controller

types/web.d.ts
Like from code examples at https://github.com/react-spring/react-with-gesture/
=> Allow update spring config from 'set' function

.gitignore, .size-snapshot.json, package.json, src/useTransition.js
Based on this convo: https://spectrum.chat/react-spring/general/in-usetransition-with-trail-can-i-animate-leave-before-animating-the-items-that-enter~badcd1d9-9fc0-41a2-a60b-e31ab3f817a6
=> [WIP] feat: adds “order” to useTransition

src/shared/helpers.test.ts, src/shared/helpers.ts
as suggested in https://github.com/react-spring/react-spring/issues/26
=> improvement types of interpolateTo helper function

src/renderprops/addons/Parallax.js
- allows setting an id attribute on <Parallax /> container
=> adds id as pass-through prop

package.json, yarn.lock
`lint-staged` is [11.5MB](https://packagephobia.now.sh/result?p=lint-staged)
`pretty-quick` is [0.4MB](https://packagephobia.now.sh/result?p=pretty-quick)
=> use pretty-quick

src/types/animated.ts
=> fix(ts): children prop of animated component

targets/three/src/FrameLoop.ts, targets/three/src/index.ts, yarn.lock
by re-adding FrameLoop class local to @react-spring/three
=> fix: make successful build 

demo/src/sandboxes/viewpager/package.json
Demo was not working in codesandbox due to dependencies not being installed
https://codesandbox.io/s/github/pmndrs/react-spring/tree/master/demo/src/sandboxes/viewpager
Add the dependencies to the packasge.json and its working now 
https://codesandbox.io/s/green-sound-ber1y?file=/package.json:0-812
=> update dependencies in non working demo

demo/src/sandboxes/notification-hub/package.json
More dependency fixes in sandboxes
https://codesandbox.io/s/wandering-wildflower-c5bvo?file=/package.json:0-723
Showed error: https://codesandbox.io/s/np7ib?file=/src/index.tsx&from-sandpack=true
=> more dependency fixes

packages/parallax/src/index.tsx
Reverts the changes from #1023. Resolves #1422.
The previous behavior was intended, but not clear. A PR for docs is incoming.
Re-added `targetScroll` to `setPosition` calculations.
=> fix(parallax): revert changes from #1023

demo/src/sandboxes/parallax-sticky/src/App.tsx, demo/src/sandboxes/parallax-sticky/src/styles.module.css
The demo was not rendering correctly in the docs iFrame
Adds a `<div>` and updates `styles.module.css`
=> fix: adjust styles to work in docs Demo

.github/PULL_REQUEST_TEMPLATE.md
PR template prompts PR submitters to read a file, `CODE_OF_CONDUCT.md` which is not present in the repo. This removes the reference from the PR template.
[Ticket](https://github.com/pmndrs/react-spring/issues/1762)
Copy change in the PR template. 
Before: 
```
```
After: 
``` 
```
=> Remove ref to non-existent Code of Conduct from PR template

packages/rafz/README.md
Minor documentation fix to avoid confusion and using other rafz already installed.
added the correct path to the rafz library under @react-spring
=> update readme to use the right rafz

README.md
There were a couple grammatical/spelling errors on the readme.md.
I fixed them. 
Big fan of react-spring. Much love to all the contributors.
=> saw two grammatical errors & fixed 'em

CONTRIBUTING.md
Fix typo in the word "preconstruct"
I have found a typo
I have corrected the typo
=> docs: typo

packages/core/src/hooks/useTransition.tsx
resolves #1948
- resolves #1948
- check if we have an internal ref we should update
=> fix: check if we have an internal ref to update

docs/app/routes/docs/components/index.mdx, docs/app/routes/docs/components/use-chain.mdx, docs/app/routes/docs/components/use-spring.mdx, docs/app/routes/docs/components/use-springs.mdx, docs/app/routes/docs/components/use-trail.mdx, docs/app/routes/docs/components/use-transition.mdx, docs/app/routes/docs/concepts/animated-elements.mdx, docs/app/routes/docs/getting-started.mdx, docs/app/routes/docs/index.mdx, docs/app/routes/docs/typescript.mdx, docs/app/routes/docs/utilities/use-isomorphic-layout-effect.mdx, docs/app/routes/docs/utilities/use-reduced-motion.mdx
There are some spelling errors scattered throughout the beta docs.
This fixes some spelling errors in the beta docs.
=> chore(docs): fix spelling issues

docs/app/routes/docs/components/use-springs.mdx
Just fix a small typo on the documentation.
=> chore(docs): fix a small typo of the hook name.

docs/app/routes/docs/guides/react-three-fiber.mdx
Typos!
- [x ] Documentation updated
=> docs: Update react-three-fiber.mdx

.github/workflows/bundle-size.yml
=> chore: add bundle-size workflow

docs/app/styles/global.ts
resolves #2138
Added a CSS rule for Firefox only:
font-variant-ligatures: none;
=> docs: add css rule for firefox font varient ligatures - issue #2138

docs/app/routes/docs.concepts.animated-elements.mdx
Noticed some grammar mistakes in the documentation about creating custom hosts, thought about improving the wording to make the language clearer.
Some grammar fixes and light rewording in the documentation to improve readability.
=> Docs: Improve grammar on `animated-elements.mdx`

docs/app/routes/docs.utilities.use-in-view.mdx
for newer developers to not feel confused or have an external resource to understand better  
added a link for developers to learn more about the intersection observer if they are not familiar with it already
=> docs: added link for intersection observer api

.github/workflows/bundle-size.yml, .github/workflows/tests.yml, package.json
=> chore(ci): fix bad spelling of package name
