examples/demos/sunburst/index.js
@drcmda Hi, I was trying make the build the examples on my machine and I'm seeing this a typo to import a component 'Partition'. 
```
ERROR in ./demos/sunburst/index.js
Module not found: Error: Can't resolve './Partition' in '/home/leonardo/Documents/react-spring/examples/demos/sunburst'
@ ./demos/sunburst/index.js 10:0-36 101:27-36
@ ./demos lazy ^\.\/.*$ namespace object
@ ./index.js
@ multi (webpack)-dev-server/client?http://localhost:8080 index.js
ℹ ｢wdm｣: Failed to compile.
```
=> Fixing path on examples.

.size-snapshot.json, package.json, rollup.config.js, yarn.lock
This plugin allows to track size changing with every commit. Also there is useful treeshakability metric which shows size after bundling `import {} from 'lib'`. This allows us to fix treeshakability explicitly without false assumptions.
P.S also I found inconsistency in naming: `dist/react-spring.js` is cjs, `dist/addons.js` is esm.
=> Add size snapshot

.size-snapshot.json, package.json, rollup.config.js, yarn.lock
- annotate-pure-calls saved only 4 bytes so it doesn't help right now
- removed react-dom from peer dependencies
- upgraded babel which is slightly increased size because of refactored helpers
This PR is mostly preparation for the next one.
=> Remove annotate-pure-calls plugin and upgrade babel

examples/demos/parallax/index.js, src/Parallax.js, src/animated/createAnimatedComponent.js
Let's change to callback refs until major release with react 16.3 restriction.
=> Replace string refs with callback refs

.size-snapshot.json, API.md, examples/demos/areas/index.js, examples/demos/gestures/index.js, examples/demos/morph/index.js, examples/demos/nativespring/index.js, examples/demos/parallax/index.js, examples/demos/reveals/index.js, examples/demos/scroll/index.js, examples/demos/spring/index.js, examples/demos/sunburst/index.js, examples/demos/timing/index.js, examples/demos/trails/index.js, examples/demos/transitions/index.js, examples/demos/tree/index.js, readme.md, src/Parallax.js, src/index.js
This pattern looks good, but it fails if we need to achieve treeshaking.
I converted docs and examples to this way
```js
import { Parallax, ParallaxLayer } from 'react-spring'
```
but still keep `Parallax.Layer` for backward compatibility.
=> Export parallax layer and tweak docs and examples to it

.size-snapshot.json, src/Transition.js
With this change we achieve 2.5 kb better treeshaking.
=> Inline default props to enable treeshaking for Transition component

.size-snapshot.json, src/Spring.js
My use case is horizontal panning using native rendering.
In the [horizontal gesture example](https://codesandbox.io/embed/jzn14k0ppy) `xDelta` is passed to `Spring`, which means every pointer move event causes a render.
This pull request allows passing an `Animated.Value` into `Spring` such that it may be manipulated outside of the render function, and also adds a `hold` prop which works like `immediate` except it makes the given animations not start.
I used this to update the animated value on pointer move events, and hold the animation for as long as the interaction lasts.
Example:
```
import { Spring, Value, animated, interpolate } from "react-spring";
class Swipe extends Component {
state = {
value: new Value(25),
wait: true
};
componentDidMount() {
setTimeout(() => …
```
=> Allow passing animated values to Spring, add hold prop

API-OVERVIEW.md, readme.md
Small fix for two links in the documentation.  Also, capitalized README.md since all the other docs were capitalized.  
---
One quick question with the docs.  I was reading up on the native and animated component.  The usage suggests `animated.div` and I noticed it works with other html elements like `animated.li`.  
I tried to get it to work with a react component `const MyDiv = props => <div>{props.children}</div>
`, but `animated.MyDiv` didn’t work.  ([https://codesandbox.io/s/l419mkpn69](https://codesandbox.io/s/l419mkpn69))  
I assume I cannot use animated with functional or class components?
=> [docs] fixed two links

src/animated/targets/react-dom/fix-auto.js
The portal-based solution resulted in inaccurate width calculations on the user's content when the content did not have a constrained width value and contained wrapping text.
This solution uses a 0-height rendering of the user's content in-place, so that all layout constraints stay consistent with intended usage. I used a little trick to get the total height based on the `scrollHeight` on the 0-height measuring element.
I'm not convinced this will work with all layouts, since we're rendering this intermediate div, which breaks any layout properties which the user's content might be getting from its parent. Still, I think this solution may fit a wider variety of use cases than the current one.
=> Move fix-auto from portal-based to in-place hidden measuring

.size-snapshot.json, package.json, rollup.config.js, yarn.lock
`es` may confuse. Material-ui uses it to distribute es6+ syntax. Our
goal is distibuting only es modules and `esm` fits better to it.
In the latest version rollup started support this esm format alias.
=> Prefer esm over es name

index.d.ts
I don't have much experience with TS, haven't had the chance to test the annotations, let me know if there's something that doesn't work.
=> First try at adding missing type annotations.

index.d.ts
A typo in typings was fixed, due to which sometimes the Transition component could not be used.
=> Fix typo in the typings

API.md
This PR adds information on the docs about the full RK4 Algorithm support of the `Spring` component.
Note: I'm not sure if the `Transition` or another component needs to be updated, for now, I will just update the `Spring` docs.
=> Improve the Spring API docs

index.d.ts
I recently encountered that TypeScript is throwing typing error when I use `<Transition />` because `children` type does not match.
When I inspected the typing file in the repo, I found out that the definition for `render` and `children` could cause some misunderstanding.
Therefore I offer a fix to this, take a look at the changes.
=> Add SpringRendererFunc typing

.size-snapshot.json, index.d.ts, package.json, tests/ts-test.tsx, tsconfig.json, yarn.lock
I noticed that the Keyframes typings don't seem to be in sync with the latest version anymore, so this should fix that.
Also changed the type defs to use interfaces as that actually allows people to extend them. For instance ParallaxLayer should also accept a `style` prop. You should be able to easily extend that as end-user. 
Also, I have no idea what all these S, DS generics are. They seem to be used all over the place even when they're not being used in the actual type / interface. See `ParallaxLayerProps` for instance. Maybe the original author knows why thats there?
=> Fix keyframes types and use interface so user can extend

.size-snapshot.json, index.d.ts, readme.md, src/Transition.js
This PR reflects some of the thought put out in https://github.com/drcmda/react-spring/issues/26#issuecomment-406741416.
From reading some of the recent PR's I can see that having a literal boolean type on `Transition` has been discussed in #84 but never seemed to have gotten implemented.
The TS compiler throws an error if a literal boolean false type is being substituted for this PR's basic boolean type. A simple type discrepancy. Therefore `boolean` is used instead.
I'll modify as needed.
Thanks for a great lib @drcmda 👍
=> Update Transition type definition

.size-snapshot.json, src/targets/web/fix-auto.js
This has no actual change in file sizes, size snapshot on master was outdated - u can see the real snapshot diff [here](https://github.com/drcmda/react-spring/commit/93f2c38547ea1889cd99212db87d6df05706b0c8#diff-29fd455fe4a1c8d19c5e5b1420ce14faL8).
the point of this PR is to avoid copying 2 arrays with spread (results of `getValues `) and creating 3 temporary arrays that have to be GCed (mentioned copies + a wrapper array that hold their values together in a way that `[]#.some` could be used)
=> Micro perf/avoid array copying

.size-snapshot.json, src/targets/shared/colorMatchers.js, src/targets/shared/normalizeColors.js
Size diff [here](https://github.com/drcmda/react-spring/commit/338e3fb5823e77df590c8ac663254bc35b40552b#diff-29fd455fe4a1c8d19c5e5b1420ce14faR7). Again it's really minimal but IMHO still worth doing - anything internal that is an object merely for namespacing purposes should be a namespace object - then rollup will be able to just use each a single variable in each using "call site" rather than an object property.
=> Namespace color matchers

documentation/Introduction.mdx, package.json
This PR allows importing `react-spring` directly in `react-native` without having to refer to `react-spring/dist/native`.
```js
// before
import { Spring } from 'react-spring/dist/native'
// after
import { Spring } from 'react-spring'
```
=> Support entry for react-native

examples/package.json
When running "npm install" & "npm build" on the examples directory I get the following traceback:
```
npm start
> react-spring-examples@1.0.0 start /Users/timo/workspace/react/react-spring/examples
> webpack-dev-server --progress --colors --env development
10% building modules 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/timo/workspace/react/react-spring/examples
✖ ｢wdm｣:
ERROR in ./index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/plugin-proposal-class-properties' from '/Users/timo/workspace/react/react-spring/examples'
at Function.module.exports [as sync] …
```
=> Add missing plugin-proposal-class-properties dependency to examples.

src/targets/web/fix-auto.js
Fixes some part of https://github.com/drcmda/react-spring/issues/249
=> Forward element key when calculating height auto

index.d.ts
I think the `onRest` callback will receive the animated value, but I haven't any experience of TypeScript, so please help me to review it, thanks!
=> Fix onRest & animated typing

index.d.ts
Related to https://github.com/drcmda/react-spring/issues/26 since this improves on the Typescript definitions.
Noticed when using the Parallax component that the ref didn't have any types describing that you can use the `.scrollTo()` function. With this, Typescript users will get complete typing and won't need to create their own or cast the ref to `any`.
=> Add explicit type definition for Parallax ref

index.d.ts
Regarding https://github.com/drcmda/react-spring/issues/275, after trying `react-spring 6.1.0`, the type issue on `TransitionItemProps` has yet to be resolved, causing an error in Typescript due to props type mismatch. (PR https://github.com/drcmda/react-spring/pull/270 doesn't seem to target this issue)
This PR adds the missing `boolean` type to the `TransitionItemProps` that gets used by the `Transition` component, as documented [here](http://react-spring.surge.sh/transition#props)
The live example of using `TransitionItemProps` as a `boolean` toggle to control mount/unmount component is demonstrated in the 2nd example in the above URL and is tested to be functioning this way.
Reference https://github.com/drcmda/react-spring/issues/26 again since this improves more on the Typescript …
=> Types: Fix TransitionItemProps not recognising booleans

documentation/Hooks-manual.mdx
Add `const` before array destructuring
=> Hotfix typo surrounding array destructuring.

documentation/Keyframes.mdx
* `preperties` => `properties`
* `spaecial` => `special`
=> Fix small typo in Keyframes Docs

index.d.ts, src/Trail.js
Currently in `<Spring />`, `<Transition />`, and `<Trail />`, the child function parameter types cannot be inferred. As an example:
```jsx
<Spring from={{ opacity: 0 }} to={{ opacity: 1 }}>
{(styles) => <div style={styles} />}
</Spring>
```
Here `styles` would be of type `any`. With the proposed changes however, `styles` would be of type `{ opacity: number, [key: string]: any }`. The `[key: string]: any` is an unfortunate side effect of needing to support passthrough props. I don't see passthrough props documented anywhere but they are used in [this demo](https://codesandbox.io/embed/oln44nx8xq) (`toggle`) so I made sure to support it in the types. If that isn't actually part of the API I can take out the `& WeakObject`'s. and make this a bit cleaner.
For `Transition` I made the …
=> Properly infer generic typings for Spring/Transition/Trail

documentation/Spring.mdx
It's tiny enough that I feel silly creating a PR 🙃
=> Fix typo in Spring docs

index.d.ts
Adjusts the return component type for `animated('div')` and `animated.div`, since they actually return the result from `forwardRef`
see [forwardRef definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a8323887d04e77b954142e388e4026cedc8e405d/types/react/index.d.ts#L693)
=> [typescript] Fix animated components to be ForwardRefExoticComponent

index.d.ts
Fixes: https://github.com/drcmda/react-spring/issues/323
Adds `after`, `reverse`, and `force` to typescript definitions for `Spring` props
=> [typescript] Adds after, reverse, and force to Spring props

readme.md
This just redirects the broken link to the contributor graph page on GitHub.
=> Fixed broken link to contributor page

readme.md
I noticed the docs site seems to support HTTPS (https://react-spring.surge.sh) and figured it would be better to link to that URL from the readme.
=> Update readme documentation link to HTTPS

index.d.ts
Another update to the TS type definitions:  https://github.com/drcmda/react-spring/issues/26
Transition was missing `onDestroyed`, `reset`, `trail`, and `unique`
=> Add missing Transition prop typings

index.d.ts
TransitionProps does not contain properties such as onStart or onRest.
=> TypeScript TransitionProps doesn't extends SpringProps

documentation/Hooks-manual.mdx
the `toggle` class property wasn't actually being set to a function
=> Fix Controller docs code example

index.d.ts
reverting commit 281993d as it introduced this issue... I looked it up in the latest react version, there is no exported member 'ForwardRefExoticComponent'
=> @types/react/index has no exported member 'ForwardRefExoticComponent'

src/Trail.js
The type specification for the `keys` property of Trail was defined twice (lines `10` and `18`), and defined differently in each case. This PR removes what looks like the incorrect definition (which also didn't match its docstring, as `keys` can be a function that maps an item to its key).
This will also result in no behavioural change, as when multiple properties are defined with the same name in an object literal, the last one is used. So this deleted code was being ignored anyway.
I found this in the alerts for this project on LGTM.com, and there are [a bunch of remaining alerts](https://lgtm.com/projects/g/drcmda/react-spring/alerts) that would probably also be good to look at.
*(Full disclosure: I'm part of the team behind LGTM.com)*
=> [chore] remove overwritten property

types/hooks.d.ts, types/universal.d.ts
Addresses what I could from https://github.com/react-spring/react-spring/issues/383, and adds types for `useChain`.
=> More TypeScript updates

.size-snapshot.json, types/hooks.d.ts
This PR adds an Opaque type that wraps `ForwardedRef` in the `react-spring` `hooks.d.ts` file. This allows for a type to be returned whose properties can be interpreted as valid CSS Properties as well as a type which can be interpolated.
eg:
```tsx
import { useSpring, animated } from 'react-spring/hooks';
interface Props {
open?: boolean;
}
function App({ open = false }) {
const { xy } = useSpring({
xy: open ? [0, 0] : [1, 1],
});
// [number, number] => string
const interpolateTransform = ([x, y]: [number, number]) => {
return `translate3d(${x * 10}, ${y * 10}, 0px) scale(${x})`;
};
// [number, number] => number
const interpolateBackgroundColor = ([x]: [number, number]) =>{
return x;
};
return (
<animated.div
style={{
backgroundColor: xy                               // [number, number] …
```
=> Allow for interpolation chaining with hooks and TypeScript

types/hooks.d.ts
Looks like this behavior was fixed in 38d26a1cb7c27fdb4587a35477caae226833bafa but the typings weren't updated to reflect that.
=> Fix `from` property type for `useTransition`

types/universal.d.ts
This PR fixes the issue regarding #386.
I believe `SpringProps` was intended to inherit `SpringBaseProps` but was mistakenly not done so. This fix let's me add props like `config` to my `Spring` components.
=> Add SpringBaseProps inheritance to SpringProps interface

types/universal.d.ts
This should make the config on TransitionProps reflect the current implementation and the docs.
=> Add `config` to TransitionProps interface

readme.md
I use React Spring quite a bit these days, which means I'm often looking to check the docs for specific APIs. And for some reason, I always have a really tough time actually finding them! 
The docs site doesn't show up at all when you google "React spring docs":
After clicking "Documentation" in that first result, I wind up in this repo, except it's a bunch of markdown files. So I navigate up to the main README, and scroll around looking for the link to the docs. This takes me several tries, since my quick-scanning brain totally misses this link:
Here's what it looks like in this PR:
I know doing READMEs is tricky because you're trying to match several usecases at once, from the beginner who doesn't know what this even is, to the returning users looking for the API reference docs. But I …
=> Emphasize docs in README

src/Transition.js, types/universal.d.ts
Updating onDestroyed to reflect what it actually does on the implementation, maybe this should also be mentioned on the docs?
The first commit of this PR has a fix for typos, but I'm not 100% sure the naming was intentional or not. If it was, let me know and I'll revert the changes.
=> Updating onDestroyed typing on TransitionProps

src/targets/native/hooks.js
Fix `ReferenceError: extendedAnimated is not defined`
=> Fix native-hooks animated export

src/Transition.js
I had to read the source to understand that conditionally setting config by key had not been removed. I think this clarifies it better.
=> chore(docs): document Transition config by key

types/universal.d.ts
Relevant to #386 
I believe Keyframes and Transition should also allow for `after` and other SpringProps, the Trail type was the most straight forward to fix though.
=> Update Trail Props to allow for all spring props

types/renderprops-universal.d.ts
When upgrading today, I got this error:
```
ERROR in [at-loader] ./node_modules/react-spring/renderprops-universal.d.ts:234:11 
TS2430: Interface 'TrailProps<TItem, DS>' incorrectly extends interface 'SpringProps<{}>'.
Property 'to' is optional in type 'TrailProps<TItem, DS>' but required in type 'SpringProps<{}>'.
```
I opened a PR to correct this error, but for unrelated reasons I was unable to confirm the fix in the project where I'm using react-spring. So I tried running tests and wasn't able to pass `yarn test` or `yarn test:ts`. 
Here are the TS errors for 8.0.1: 
```bash
brendan ~/P/t/react-spring> yarn test:ts
yarn run v1.13.0
$ tsc --noEmit
types/native-hooks.d.ts:1:15 - error TS2307: Cannot find module './hooks'.
1 export * from './hooks'
~~~~~~~~~ …
```
=> Require `to` prop to correctly extend SpringProps

types/renderprops-universal.d.ts
```bash
node_modules/react-spring/renderprops-universal.d.ts:234:11 - error TS2430: 
Interface 'TrailProps<TItem, DS>' incorrectly extends interface 'SpringProps<{}>'.
Types of property 'to' are incompatible.
Type 'DS | undefined' is not assignable to type '{}'.
Type 'undefined' is not assignable to type '{}'.
234 interface TrailProps<TItem, DS extends object = {}> extends SpringProps {
~~~~~~~~~~
```
---
and related PR #481.
@BrendanBerkley says
> Error 5 is what my one-character PR attempted to fix, and my other code snippet is the new error that happens once I did so. There's a type mismatch with `children`, and I don't know how to fix that.
As far as read the document, `to` props should not be required in the first place. (https://react-spring-renderprops.surge.sh/spring#props) 🤔 
So, …
=> Fix TrailProps interface incorrectly extends SpringProps

types/web.d.ts
```
Argument of type 'null' is not assignable to parameter of type 'string | number | ReadonlyArray<string | number> | ((item: boolean) => string | number)'.
```
https://github.com/react-spring/react-spring/issues/495#issuecomment-461192304
=> fix useTransition keys type

types/web.d.ts
Doing this one because I was checking the `getForwardProps` function from helpers.ts and having some problems to type it when I realized it was just because I was using this list for the types when the actual implementation was different.
=> ExcludedProps update to reflect actual implementation

src/animated/createAnimatedComponent.test.tsx, src/animated/createAnimatedComponent.tsx
Components wrapped in `animated` will now have their `style` prop type modified to also accept `Animated` values. For now nothing returns this type, but in the future all API:s should return values matching the `Animated` type, to make sure there is a type error if you try to assign the return value from e.g. `useSpring` to a non-animated component (this happens to me a lot, where I miss if a styled-component wraps `animated.div` or just `div`).
@Jessidhia do you think this makes sense as a basis for how to continue typing the public API:s?
The added test cases are both to test the types and the implementation. The types can be improved (I'm still learning) and moved to another file when we share them, but at least now we have tests and a start.
=> Add better types to Animated component

types/web.d.ts
This adds the `onDestroyed` and `initial` props to `useTransition`
=> Add missing useTransition types

types/web.d.ts
The `useSprings` typings prevent [this](https://codesandbox.io/embed/n9vo1my91p) example. Updated typings to give the index in the callback function.
=> Add index arg to `useSprings` `getProps` fn typings

src/useTransition.js
Fixes: https://github.com/react-spring/react-spring/issues/461
The logic recreating the ordering of the items requires the deleted items to have consistent ordering. This seems to be already fixed in Transition.js.
Btw there seems to be other differences between Transition.js and useTransition.js even though they probably should be deduplicated.
=> Fix ordering of deleted items

types/web.d.ts
The code/docs allows for `enter`, `leave`, and `update` to be arrays, but the typings didn't, and this fixes that.
=> Allow arrays for enter/leave/update in useTransition typings

types/lib/useTransition.d.ts
The docs say you can pass `null` to `initial`, but the types don't allow it.
=> V9: Add null as an option for Transition#initial

types/renderprops-native.d.ts
Using renderprops api with react native and typescript was leading to a missing types error:
```js
import { Spring } from 'react-spring/renderprops-native'
```
```
Could not find a declaration file for module 'react-spring/renderprops-native'. 
```
=> add missing react native renderprops types file

CONTRIBUTING.md
Removed section on exclusive-deps since it doesn't connect monorepo dependencies (whereas yarn link does)
=> docs: add section for react hooks help for resolving react for hooks

targets/web/src/AnimatedStyle.ts, targets/web/src/animated.test.tsx
Fixes this: https://github.com/react-spring/react-spring/pull/782#issuecomment-526255242
=> fix: transformOrigin and transformStyle are correctly passed as CSS props

packages/core/src/useSpring.ts
Should be 2 for testing `arguments.length` in `useSpring(props, deps)`.
=> Incorrect return value from useSpring using deps

packages/core/src/Animation.test.ts, packages/core/src/Animation.ts
Hi, this is using the formula I found [in this article](https://medium.com/ios-os-x-development/demystifying-uikit-spring-animations-2bb868446773), which seems consistent with  [apple's guidelines](https://developer.apple.com/videos/play/wwdc2018/803/?time=2117). I used it to make [this interactive demo](https://spring-playground.netlify.com/). 
I wasn't sure whether to add more logic around guarding against invalid values, please let me know if that would be preferred.
(This pr was made in response to [this comment by @aleclarson](https://github.com/react-spring/react-use-gesture/issues/109#issuecomment-554409570).)
=> Update formula for frequency response

packages/animated/src/withAnimated.tsx
I found out this bug when I'm working on #903: When we pass arrow function component, it will throw error because in `createAnimatedComponent` we check `Component.prototype.isReactComponent` to check if it's component created by `create-react-class`, but arrow function doesn't have `.prototype` property. This commit additionally check if `.prototype` exists to make arrow function component can work with `animated()`.
To test this just try to pass an arrow function component into `animated()`.
=> Bugfix: make `animated` work with arrow function component

packages/core/src/Controller.ts, packages/core/src/types/spring.ts, packages/core/src/useSprings.ts, packages/core/src/useTransition.tsx
Add `pause` and `resume` method in `Controller`, `useSprings` and `useTransition` ref api. I have tried it on my own project and it looks great. If needed I can make a minimal demo.
This change will close #903 .
=> [Feature] Add resume and pause method into useTransition/useSpring ref api

packages/core/src/SpringContext.test.tsx, packages/core/src/SpringContext.tsx, packages/core/src/SpringValue.ts, packages/core/src/hooks/useSprings.ts, packages/core/src/hooks/useTransition.tsx, packages/core/src/index.ts
=> feat: add SpringContext component

packages/shared/package.json, packages/shared/tsconfig.json, scripts/prepare.js, yarn.lock
Enabled tslib to prevent emitting helpers with top level `this` which
does not exist in es modules. For some reason tslib has different and
correct helpers.
Commonjs artifacts are moved into cjs folder. Added esm folder near it.
package.json routes are created for each module via cherry-pick package.
=> Add esm support to shared package

.github/ISSUE_TEMPLATE/question.md
linking to **GitHub discussions** instead of **spectrum** as suggested in https://spectrum.chat/react-spring/general/moving-over-to-github-discussions~1e82c200-0f8f-48b5-9ef4-6ef123caf838
=> Issue template: spectrum -> github discussions

packages/animated/src/withAnimated.tsx
#1185
I think the issue was that we were not calling applyAnimatedValues on the first render (which is getting called on the first render in v8) and thus scroll top was not working. I was able to reproduce and fix it on my local.
=> fix: scrollTop is not set when from & to are equal #1185

.codesandbox/ci.json, .vscode/react-spring.code-workspace, .vscode/settings.json, demo/package.json, demo/src/App.tsx, demo/src/sandboxes/card/package.json, demo/src/sandboxes/card/public/index.html, demo/src/sandboxes/card/src/App.tsx, demo/src/sandboxes/card/src/index.css, demo/src/sandboxes/card/src/index.tsx, demo/src/sandboxes/gooBlobs/package.json, demo/src/sandboxes/gooBlobs/public/index.html, demo/src/sandboxes/gooBlobs/src/App.tsx, demo/src/sandboxes/gooBlobs/src/index.css, demo/src/sandboxes/gooBlobs/src/index.tsx, demo/yarn.lock, package.json
Adds codesandbox CI, using the *outdated* examples from `react-spring`'s site
=> Add Sandbox CI

package.json, packages/core/src/hooks/useTransition.test.tsx, packages/core/tsconfig.json, yarn.lock
As we talked in discord, for some machines, testing doesn't have MessageChannel API, so I pollyfilled it and removed the error message to work properly.
=> fix: fix message channel error

scripts/prepare.js
See #1414 
Fix the prepare JS script
Fix #1414
=> Use tilde range dependencies for stable releases

packages/core/src/Controller.test.ts, packages/core/src/Controller.ts, packages/core/src/SpringValue.test.ts
resolves #1419
check if _changed.size is larger than 0 to and the spring has not started to fire the `onStart` event handlers. In the case of setting `immediate` `_active` set is added then taken away to quickly for the event to fire. However the value has changed. We should do a double check to avoid this edge case.
=> Fix: Ensure onStart & onRest are called when immediate is true

packages/parallax/src/index.tsx
Resolves #1454. Parallax will now animate `scrollTo` correctly.
Changed the destructuring of the `value` of  `controller` in `onChange`.
I also added a line at 212 to set the `controller`'s value to `state.current` before animating because otherwise it started with stale state (In the current version `state.current` will cause the `controller` to always start at the number from the previous call to `scrollTo`).
=> fix(parallax): scrollTo gets correct scroll value

packages/shared/src/createInterpolator.test.ts, packages/shared/src/stringInterpolation.ts
This PR prevents strings like `grayscale` from being interpolated as `gray` and `scale` (color & range). This is seen in #1452.
Here's their sandbox but with this fix: https://codesandbox.io/s/grayscale-demo-react-spring-mq1wl.
I updated the regex in the shared string interpolator to ignore color names that are immediately followed by alphanumerical characters.
Previously, I had this also check preceding characters, but I couldn't find a use-case for this, and the regex for that [isn't well supported](https://caniuse.com/js-regexp-lookbehind).
- ~~Documentation updated~~
- ~~Demo added~~
=> Fix: Ignore partial color names when interpolating strings.

demo/src/sandboxes/parallax/src/styles.module.css, packages/parallax/src/index.tsx
Currently, when `Parallax` has `horizontal={true}`, all `ParallaxLayer`s still translate vertically unless `horizontal={true}` is manually set on all of them. This change makes it so `ParallaxLayer`s' default `horizontal` matches `Parallax`'s.
* Added `horizontal` to `IParallax` interface and `Parallax`'s `state`
* Added a check in `ParallaxLayer` to see if `horizontal === undefined` and reassign it if it is.
* Removed a CSS rule in sandbox demo that was causing numbers to appear too far to the left.
You can test this by looking at the sandbox demo "Parallax" (not vert). Currently, when you scroll horizontally, the layers still translate vertically.
This might be a breaking change if anyone is relying on this behavior, but it wouldn't affect anyone who has already manually set …
=> fix(parallax): child horizontal prop defaults to parent's

CONTRIBUTING.md
This PR adds instructions for contributors who are facing Windows permission errors with Preconstruct. This is a follow-up to #1459.
Updated CONTRIBUTING.md.
=> docs: add Windows instructions to CONTRIBUTING.md

demo/src/sandboxes/simple-transition/src/App.tsx, packages/core/src/hooks/useTransition.test.tsx, packages/core/src/hooks/useTransition.tsx
`useTransition` was not passing its ref as part of the payload, this the controllers (each item has a controller) were not being attached. This caused failures in instances such as useChain. 
This resolves #1453 
Pass the ref as part of the payload. However, when passing a ref, transitions will not be called unless `ref.start` is called, this is important and an example of what this looks like can be seen here: https://codesandbox.io/s/goofy-allen-u4hml?file=/src/App.tsx
I've also added the same API pattern that `useSprings` has, where only supplying a function as a prop argument will return a ref like so:
```js
const [transition, transApi] = useTransition(items, () => ({ ...props }))
```
=> [fix] useTransition ref handling

packages/core/src/hooks/useTransition.tsx
resolves #1099 
Since we handle the trail prop in `useTransition` and pass that as our `delay` prop to the `Controller` we therefore need to call the original `delay` prop from the props passed and add that to the `payload` to ensure timings are correct.
=> [fix] Delay conflict with Trail in useTransition

packages/core/src/SpringRef.ts, packages/shared/src/deprecations.ts
resolves #1423
Replace the string call with a `Proxy`. This isn't supported by ie11, but officially we don't support it.
There could be performance downsides so we need to test.
=> fix: csp issue in SpringRef

packages/core/src/Controller.ts, packages/core/src/hooks/useSprings.ts, packages/core/src/hooks/useTransition.tsx
resolves #1096 
We attach our springs to the `Controller` in a useEffect hook however the life cycle of hooks means the `setState` hook is called before any `useLayoutEffect` or `useEffect` hooks are called so our `SpringValue`s are destroyed and lost never being added to the `Controller`.
Instead when we create springs, we attach them to the `Controller` immediately preserving them.
=> [Fix] springs sometimes return undefined

demo/src/sandboxes/card/src/App.tsx, packages/core/src/Controller.ts, packages/core/src/SpringRef.ts, packages/core/src/hooks/useSpring.test.tsx, packages/core/src/hooks/useSpringRef.ts, packages/core/src/hooks/useSprings.ts, packages/core/src/hooks/useTransition.test.tsx, packages/core/src/hooks/useTransition.tsx, packages/shared/src/deprecations.ts, targets/web/src/types/__tests__/useSpring.tsx
To resolve #1423. In short the current way we're allowing people to call the `SpringRef` as they used to in v8 is to extend the `SpringRef` class from `Function` this creates issues with CSPs. Therefore we're at a fork in the road of implementing this PR, or simply removing the functionality earlier than expected.
Currently i've created a wrap-around function named `CallbableSpringRef`. It should allow you to do:
```js
const [styles, start] = useSpring(() => ({
from: { width: 0 },
to: { width: 100 }
}))
start()
```
This keeps in line with a feature we brought back in `9.1.0` to ease people into the new v9 [imperative API](https://react-spring.io/common/imperatives-and-refs#api-methods). However this will be deprecated in the future.
It's a bit messy with the TS but I really do see this a …
=> [Fix] csp issue

packages/parallax/src/index.tsx
Found this bug while making the new demo for testing (I didn't even set up `cypress` yet :sweat_smile:):
If more than 2 layers are sticky on the same page, their positions may be suddenly shifted down a page before becoming sticky when scrolled to a second time (depending on their order in the HTML). Description might not be totally clear, but you can see what I mean here: https://codesandbox.io/s/nifty-night-j6xdm?file=/src/App.tsx. 
Obviously, I had to discover this the day *after* 9.2.0 released.
Instead of having conditional position properties like this:
```javascript
[layer.horizontal ? 'left' : 'top']: 0
```
All four are now listed explicitly (`top: 0, bottom: 0`, etc..). This has no effect on regular layers.
In the future when the `inset` property has [more …
=> fix(parallax): add position properties to layer

packages/animated/src/AnimatedArray.ts, targets/web/src/animated.test.tsx
Fixing bug https://github.com/pmndrs/react-spring/issues/1430
Implemented suggested fix by a user in that thread, and wrote a unit test too.
I confirmed that the unit test failed in the expected way when the fix was not applied - i.e. spring of [10,20] is then updated to [11,21], but the resulting prop on animated div is still [11,20], because only the first animated value in the array was being updated.
=> fix: update all values of animated array (#1430)

packages/shared/src/globals.ts
Fixes #1559 
Import type declarations from `@react-spring/rafz` instead of `packages/rafz`
- Documentation updates: Not required
- Demo: Not needed
- Ready to be merged: Yes
=> fix(support): incorrect type imports for rafz

demo/src/sandboxes/image-fade/src/App.tsx, demo/src/sandboxes/simple-three/src/App.tsx, packages/parallax/src/index.tsx, targets/web/src/applyAnimatedValues.ts
Code isn't being used or don't have a purpose
Unused code isn't needed in the code and thus now remove.d
Let the IDE rage over the source code and fix the valid cases of unused/unreachable code.
=> refactor: remove unused code

packages/shared/src/helpers.ts
Fix issue [1582](https://github.com/pmndrs/react-spring/issues/1582)
[eachProp](https://github.com/pmndrs/react-spring/blob/26bd8f153dd9284915b6fbc2bc299320c44b593d/packages/shared/src/helpers.ts#L47) function accepts argument [primitives](https://github.com/pmndrs/react-spring/blob/26bd8f153dd9284915b6fbc2bc299320c44b593d/targets/web/src/primitives.ts#L2) which type is `Array`. 
Iteration works over `Array.prototype` and in case there is a `boolean` it throws an error. It should use only values from [primitives](https://github.com/pmndrs/react-spring/blob/26bd8f153dd9284915b6fbc2bc299320c44b593d/targets/web/src/primitives.ts#L2) and should not iterate over `Array.prototype`.
=> Fix issue 1582

packages/core/src/helpers.ts, packages/core/src/hooks/useTransition.test.tsx, packages/core/src/hooks/useTransition.tsx
This change does fix #1581. I'm not sure if this is the right change though, given the comment above the code.
Add `immediate` back to the array of default props to allow `useTransition({ immediate: true })` to be respected again.
If this is indeed a proper fix, I'd like to add a test somewhere. Any help with that would be great.
=> fix: add `immediate` to payload in useTransition hook

packages/parallax/README.md
The `README` still reflects pre-v9.0.0 API.
It's basically the same as the docs site with a few minor changes:
* added example installation snippet so people know it's a separate package
* expanded the example code snippet to highlight more API usage
* demo iframes are replaced with links to their respective sandboxes
=> chore: update parallax README

packages/shared/src/helpers.ts
Resolves https://github.com/pmndrs/react-spring/issues/1649: using for-in to traverse Arrays is normally safe, but with Ember's observability polyfills, it causes `createHost` to break on primitive iteration.
This fix swaps iteration to use a for loop when the traversed object is an array.
=> Fix iteration across arrays to avoid conflict with polyfilled Array variants

docs/src/pages/common/interpolation.mdx
Url to react-spring repository is broken on interpolation docs page.
Changed url to a proper one
=> Docs/fix: broken repo-url in interpolation docs page

docs/src/pages/basics.mdx
Resolves #1639 by documenting an issue with combining `animated` with `forwardRef` and explaining how to work around it.
I've updated the documentation to describe the problem in detail with examples and describe a workaround.
=> docs: Describe combining ref forwarding with `animated`

docs/src/components/CodeBlock/reactLiveScope.tsx, docs/src/pages/changelog.mdx, docs/src/pages/common/configs.mdx, packages/core/src/AnimationConfig.ts, packages/core/src/constants.ts
=> feat: add easing functions to `react-spring`

packages/parallax/src/index.tsx
It fixes the following issue: https://github.com/pmndrs/react-spring/issues/1766
Also, you can check an example here:
https://codesandbox.io/s/react-spring-parallax-issue-1766-f4iow?file=/src/App.js
I have changed the way the property `overflow` is provided to the Parallax component, instead of mixing the shorthand and the non-shorthand properties, I'm using only non-shorthand.
It will avoid this:
=> fix: update overflow css property without mixing shorthand and non-shorthand properties

packages/core/package.json
See here: https://blog.opencollective.com/beyond-post-install/
Also fixes #1668
After this change you now use the `"funding"` field like everyone else.
=> Use standard funding mechanism

docs/src/pages/hooks/use-chain.mdx
This PR fixes a typo in the docs for the `useChain` hook here: https://react-spring.io/hooks/use-chain#overview –  `correspend` -> `correspond`:
Along the way it slightly restructures the sentence by moving the definite article before the first of the two corresponding nouns.
=> chore(docs): fix typo (correspend -> correspond)

docs/src/pages/common/imperatives-and-refs.mdx
There are missing commas in the api object.
There are now sufficient commas in the object.
=> Fix missing commas in api object

README.md, docs/src/pages/index.mdx, packages/react-spring/README.md
Minor link change + updated style to include ellipsis inside the link.
Before:
After:
=> refactor: fix link to repo dependents

targets/native/src/animated.ts
It fixes the issue described here: https://github.com/pmndrs/react-spring/pull/1705/files#r913068712
I have made the `children` property optional on the `AnimatedComponent` component.
I tested this out in my project by editing the file in `node_modules`, making the same change as proposed here.
=> fix: make children on AnimatedComponent optional

.changeset/gentle-students-wonder.md, packages/core/src/hooks/useTransition.tsx
- resolves #1890 
When attaching refs to `useTransition` the animations were automatically starting regardless of the fact they shouldn't be.
This meant animations were freely running when they shouldnt be.
This problem could be the cause of #1933
- Adds test to ensure animation does not start when a ref is attached
- reattaches refs to controllers when transitions are apparent when the component is mounted
=> fix: useTransition would not obey refs

docs/app/routes/docs/index.mdx
Spelling and grammar mistakes are present in the overview section
Fixed spelling mistakes and improved grammar
=> chore(docs): fix spelling and grammar

docs/src/pages/guides/accessibility.mdx
- `useReducedMotion` was included in `react-spring` at [v9.5.0](https://github.com/pmndrs/react-spring/releases/tag/v9.5.0)
- https://github.com/pmndrs/react-spring/pull/1886
=> chore(docs): Update accessibility.mdx

.changeset/config.json, .changeset/cuddly-dolls-sit.md, .changeset/pre.json, packages/core/src/hooks/useSpring.ts, packages/core/src/hooks/useSprings.ts, packages/core/src/hooks/useTrail.ts, packages/core/src/hooks/useTransition.tsx
* resolves #1985 
* make it more verbose by validating S extends L in ternary thus support TS < 4.7 again
=> fix: remove infer S extends L

docs/app/routes/docs/components/use-transition.mdx
There was a typo in the docs.
Rephrased the sentence.
=> fix(docs): remove typo

docs/app/components/HomeBlocks/HomeBlockImperative.tsx, docs/app/components/HomeBlocks/HomeBlockTarget.tsx
It seems the link buttons in document is broken. Both imperatives and target. Also, it seems target concept document is not introduce yet but I believe it would be under `/docs/concept/target` for sure.
Correct both of incorrect links.
=> fix(docs): imperative and target links in homepage

docs/app/routes/docs/concepts/targets.mdx
typo
fixed a typo
Changed middeleware to middleware
=> docs: Update targets.mdx fixed a single typo (Middeleware to middleware)

docs/app/routes/docs/utilities/use-resize.mdx
fix Typescript section of useResize documentation
Wrong function name in documentation
Just changed function name in documentation
It is just a fix for useResize documentation.
=> docs: fix typo in `useResize` Docs (wrong function name)

docs/app/routes/docs/utilities/use-resize.mdx, packages/core/src/hooks/useResize.ts
Fixes a small typo in `useResize` docs.
=> docs: fix a typo in `useResize` docs (obsere → observe)

docs/app/routes/docs/concepts/animated-elements.mdx
I ran to this error today while I was reading the [animated components section](https://www.react-spring.dev/docs/concepts/animated-elements#animating-components).  The example I was trying to implement is the one attached in the code below.
I'm using Next.js and the error has been resolved once I updated the type of `to.y`: `string`, instead of  `to.y`: `number`.  
<div  align="left" dir="auto">
</div>
- Change the type of `to.y` coordinate to match the one used in `from.y`; which is happen to be a string in this example.
=> docs(fix): cannot animate between AnimatedString and AnimatedValue, as the "to" prop suggests

.changeset/strange-falcons-confess.md, docs/app/routes/docs/advanced/spring-ref.mdx, packages/core/src/SpringRef.ts
* resolves #1725
* SpringRef.set now accepts a function meaning you can `set` different Controllers
=> feat: enable SpringRef.set to be called with a function

docs/app/data/fixtures.tsx, docs/app/routes/docs/utilities/use-resize.mdx, packages/core/src/hooks/useResize.ts
Allow to pass nullish container references to `useResize`.
Extended type of `useResize` to allow `null` and `undefined` as reference value types as well.
=> fix: allow container ref with null and undefined for useResize

cypress/integration/parallax.spec.js, docs/app/data/fixtures.tsx, packages/core/src/hooks/useSpringValue.test.ts
Just a simple typo fix, nothing more
=> Fix typo in docs, fix same typos in internal code

.changeset/cool-brooms-boil.md, packages/core/src/types/objects.ts
Some open-source and largely used libraries such as nivo directly bind to the types being declared by `@react-pring/core` in some of their code.
For instance in nivo, the following code:
```ts
import { SpringValues } from '@react-spring/web'
//...
export interface NodeProps<Datum extends object> {
//...
animatedProps: SpringValues<NodeAnimatedProps>
//...
}
```
Implicitely force nivo to be able to reference parts of the typings of `@react-spring/core` into their d.ts files if they want to be able to publish their package. It basiaclly results into `Partial<import("@react-spring/core").AnimationConfig>` in the produced d.ts at some point. And as a consequence TypeScript complains with the error `error TS4023: Exported variable 'htmlDefaultProps' has or is using name 'AnimationConfig' from …
=> fix: Export missing type `AnimationConfig`

.changeset/config.json, .github/workflows/bundle-size.yml, .github/workflows/experimental.yml, .github/workflows/nightly.yml, package.json, scripts/version-and-publish.sh
* Adds a nightly build
* Cleans up others
=> chore: update workflows

docs/app/routes/docs/concepts/targets.mdx
correct spelling of 
"changes -> ""chances" 
"too" -> "to"
There were some spelling errors in the documentation.
Corrected the spelling errors to what I thought was the correct grammar.
Changes:
This is my first open source pr :)
=> docs: spelling fixes

docs/app/routes/docs/advanced/spring-value.mdx
Incorrect usage of "resume" in the [documentation](https://react-spring.dev/docs/advanced/spring-value#reset)
Fixed incorrect usage of "resume" instead of "reset"
=> doc: Fixed incorrect usage of "resume" instead of "reset"

docs/app/routes/docs/concepts/controllers-and-springs.mdx, docs/app/routes/docs/guides/testing.mdx
Fixing the [misspelling of in fact.](https://en.wiktionary.org/wiki/infact)
Small typo in documentation.
Corrected totally 3 `infact` occurrences in 2 files.
=> docs: typo infact fix

docs/app/routes/docs/guides/testing.mdx
Hello :)
There is a little typo in the testing guidelines visible [here](https://www.react-spring.dev/docs/guides/testing#skipping-animations):
=> docs: fix typo in testing guidelines

docs/app/routes/docs/concepts/imperative-api.mdx
A small change in docs to make it more readable. 
Fixed spelling mistake comparions -> comparisons.
Fixed spelling mistake comparions -> comparisons.
I have fixed a spelling mistake comparions -> comparisons.
=> Type Error in docs: /docs/concepts/imperative-api#comparison

docs/app/routes/docs.advanced.async-animations.mdx, docs/app/routes/docs.concepts.targets.mdx
- [format "The to prop" in async-animations.mdx](https://github.com/pmndrs/react-spring/commit/2bb9a761470bcc47188d8627d7e51dd5b5cec200)
- [fix spelling of "targetting"/"targetted" in targets.mdx](https://github.com/pmndrs/react-spring/commit/983de89f5f39630022f6f47617080fe85eeac7d5)
=> minor docs improvements

docs/app/routes/docs.components.use-spring.mdx
=> docs: fix link

docs/app/data/fixtures.tsx
In the Overview section of this doc, we have the Getting Started Card. Its body text was "Learn about how use react-spring with step by step explanations". It is grammatically incorrect.
So, I changed it to "Learn about how to use react-spring with step-by-step explanations". Added "to" after the word about and changed the text step by step to "step-by-step".
=> Typo error in fixtures.tsx

.changeset/stale-owls-double.md, packages/shared/src/hooks/useReducedMotion.ts
Currently, calling `useReducedMotion` on a Safari browser older than v14 causes an error, crashing the app.
This pull request adds compatibility checks, so that `useReducedMotion` can be called on older devices without producing an error.
Resolves https://github.com/pmndrs/react-spring/issues/2299
Adds truthy checks to `MediaQueryList.addEventListener` before attempting to call the function. This function is undefined on older browsers.
=> fix: add `useReducedMotion` compatibility for Safari 13 and older

docs/app/data/fixtures.tsx
The naming of `immediate` _suggests_ target styles will be applied instead of running the animation, but this isn't explicitly stated. This makes me unsure of whether I should be using `immediate` when wanting to skip motion.
Clarifies what `immediate` does to 'prevent' animation
=> Clarify what `immediate` does
